version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: cimg/openjdk:8-jdk
    steps:
     
      - checkout
     
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
     
      - run:
          name: Test
          command: mvn test

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  version: 2
  build-then-test:
    jobs:
      - build
      - test:
          requires:
            - build